name: flutter_application_onjungapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.0.7
  dotted_border: ^2.0.0
  flutter_riverpod: ^2.3.6 # Riverpod core
  hooks_riverpod: ^2.3.6 # Hooks support (선택)
  flutter_hooks: ^0.21.2 # Flutter Hooks (선택)
  uuid: ^4.0.0
  collection: ^1.17.2
  kakao_flutter_sdk: ^1.9.7+3
  kakao_flutter_sdk_auth: ^1.9.7+3
  kakao_flutter_sdk_user: ^1.9.7+3
  sign_in_with_apple: ^7.0.1
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
